---



sudo subscription-manager repos
    --enable rhocp-4.12-for-rhel-8-$(uname -i)-rpms
    --enable fast-datapath-for-rhel-8-$(uname -i)-rpms

sudo yum install -y yum-utils createrepo

sudo reposync --arch=$(uname -i) --arch=noarch --gpgcheck \
    --download-path /var/repos/microshift-local \
    --repo=rhocp-4.12-for-rhel-8-$(uname -i)-rpms \
    --repo=fast-datapath-for-rhel-8-$(uname -i)-rpms

sudo find ${REPO_PATH}/microshift-local -name \*coreos\* -exec rm -f {} \;

sudo createrepo ${REPO_PATH}/microshift-local

sudo tee ${REPO_PATH}/microshift-local/microshift.toml > /dev/null <<EOF
id = "microshift-local"
name = "MicroShift local repo"
type = "yum-baseurl"
url = "file:///${REPO_PATH}/microshift-local/"
check_gpg = false
check_ssl = false
system = false
EOF

sudo composer-cli sources add ${REPO_PATH}/microshift-local/microshift.toml

```
name = "minimal-microshift"

description = ""
version = "0.0.1"
modules = []
groups = []

[[packages]]
name = "microshift"
version = "4.12.0-1"

[customizations.services]
enabled = ["microshift"]
```




