---

# https://www.opensourcerers.org/2023/11/20/kubernetes-at-the-edge-microshift-on-raspberry-pi-4-using-fedora-iot/
# https://www.opensourcerers.org/2022/01/17/openshift-on-raspberry-pi-4/
# https://medium.com/@ben.swinney_ce/openshift-raspberry-pi-2e78f2990395

# need to serve the image on a web server accessible to the local network
# a. Option 1: ownload the image and offer it up via podman from the macos host interface
#    - this would require opening the firewall to allow access to network interface (8000?)
#    https://www.youtube.com/watch?v=XNkIOYvCPWY
# b. Option 2: Can image be served through cockpit on the Imager Builder host directly?

sudo subscription-manager repos
    --enable rhocp-4.12-for-rhel-8-$(uname -i)-rpms
    --enable fast-datapath-for-rhel-8-$(uname -i)-rpms

sudo yum install -y yum-utils createrepo

sudo reposync --arch=$(uname -i) --arch=noarch --gpgcheck \
    --download-path /var/repos/microshift-local \
    --repo=rhocp-4.12-for-rhel-8-$(uname -i)-rpms \
    --repo=fast-datapath-for-rhel-8-$(uname -i)-rpms

sudo find ${REPO_PATH}/microshift-local -name \*coreos\* -exec rm -f {} \;

sudo createrepo ${REPO_PATH}/microshift-local

sudo tee ${REPO_PATH}/microshift-local/microshift.toml > /dev/null <<EOF
id = "microshift-local"
name = "MicroShift local repo"
type = "yum-baseurl"
url = "file:///${REPO_PATH}/microshift-local/"
check_gpg = false
check_ssl = false
system = false
EOF

sudo composer-cli sources add ${REPO_PATH}/microshift-local/microshift.toml

```
name = "minimal-microshift"

description = ""
version = "0.0.1"
modules = []
groups = []

[[packages]]
name = "microshift"
version = "4.12.0-1"

[customizations.services]
enabled = ["microshift"]
```




