---

- name: Check that the install image iso exists
  stat:
    path: "{{ image_builder.image_path }}"
  register: image_exists_stat

- name: Assert that the install image iso exists
  ansible.builtin.assert:
    that: image_exists_stat.stat.exists
    fail_msg: "RHEL ISO does not exist: {{ image_builder.image_path }}"


- name: Create UTM VM for Image Builder
  ansible.builtin.include_role:
    name: utm
    tasks_from: create.yml
  vars:
    utm_clean_vm: true
    utm_vm_name: "{{ image_builder.vm_name }}"
    utm_boot_iso: "{{ image_builder.image_path }}"
    utm_vm_cores: "{{ image_builder.cores }}"
    utm_vm_memory: "{{ image_builder.memory_gb | int * 1024 }}"
    utm_cidr_length: "{{ image_builder.cidr_length }}"
    utm_icon: "{{ image_builder.icon }}"
    utm_backend: "{{ image_builder.apple_hypervisor | upper }}"
    utm_vm_arch: "{{ image_builder.arch }}"
    utm_disk_primary_size_gb: "{{ image_builder.root_disk_gb }}"
    utm_disk_secondary_enabled: false
    utm_qemu_debug_log: true


- name: "Set the boot ISO for the VM: {{ image_builder.image_path }}"
  ansible.builtin.include_role:
    name: utm
    tasks_from: set_iso.yml
  vars:
    utm_vm_name: "{{ image_builder.vm_name }}"
    utm_boot_iso: "{{ image_builder.image_path }}"
    utm_disk_secondary_enabled: false

- name: Start the VM 
  ansible.builtin.include_role:
    name: utm
    tasks_from: start_vm.yml
  vars:
    utm_vm_name: "{{ image_builder.vm_name }}"
    utm_start_seconds: 20

- name: Show MAC and IP address
  debug:
    msg:  
    - "IP: {{ utm_vm_ip_addr }}, MAC: {{ utm_vm_mac_addr }}"    

- name: Put Route53 DNS update
  ansible.builtin.include_role:
    name: route53_subdomain
  vars:
    route53_register_wait: no
    route53_subdomain_action: create
    route53_subdomain_user_access_key: "{{ route53_user_access_key_id }}"
    route53_subdomain_user_secret: "{{ route53_user_secret_access_key }}"
    route53_subdomain_records:
      node_forward:
        record: "{{ rhel_fqdn }}"
        value: "{{ utm_vm_ip_addr }}"
        zone: "{{ image_builder.hostedzone }}"
        type: A






