---

- name: Fetch AWS admin credentials from 1Password for least privilege Route53 subdomain user
  hosts: localhost
  gather_facts: no
  tasks:

  - name: Fetch secrets
    ansible.builtin.set_fact:
      cacheable: true
      admin_vault:
        route53_owner_access_key: "{{ lookup('community.general.onepassword', admin_vault_1password_mapping.route53_owner_access_key.name, field=admin_vault_1password_mapping.route53_owner_access_key.field) }}"
        route53_owner_secret: "{{ lookup('community.general.onepassword', admin_vault_1password_mapping.route53_owner_secret.name, field=admin_vault_1password_mapping.route53_owner_secret.field) }}"
   