---

- import_playbook: instance_facts.yml

- name: Populate 1Pasword Vault items for target cluster
  hosts: client
  gather_facts: no
  tasks:

  - name: Populate 1Password with cluster login secret
    when: onepass_enabled
    ansible.builtin.include_role:
      name: vault_utils_1password
      tasks_from: set_item.yml
    vars:
      category: login
      name: "Login {{ cluster_full_name }}"
      fields:  
      - field: "username"
        value: "kubeadmin"
        type: text
      - field: "password"
        value: "{{ instance_kubeadmin }}"
        type: password
      - field: "website"
        value: "{{ instance_console_url }}"
        type: text
      - field: "auth"
        value: "{{ instance_oauth_url }}"
        type: text
      - field: "API"
        section: automation
        value: "{{ instance_api_url }}"
        type: text
      - field: "IP"
        section: automation
        value: "{{ instance_ip_addr }}"
        type: text
      - field: "MAC"
        section: automation
        value: "{{ instance_mac_addr }}"
        type: text
      - field: "ssh_key_public"
        section: automation
        value: "{{ ssh_key_public }}"
        type: text
      - field: "ssh_key_private"
        section: automation
        value: "{{ ssh_key_private }}"
        type: password
      - field: "kubeconfig_path"
        section: automation
        value: "{{ instance_kubeconfig_path }}"
        type: text
      - field: "agent_dir"
        section: automation
        value: "{{ instance_agent_dir }}"
        type: text


