---

- name: Create 1Pasword Vault items for manual entry
  hosts: client
  gather_facts: no
  tasks:

  # aws admin secrets item
  - name: Inialize AWS Route53 Admin vault item
    when: onepass_enabled
    ansible.builtin.include_role:
      name: vault_utils_1password
      tasks_from: set_item.yml
    vars:
      category: server
      name: "{{ onepass_aws_admin_vault_item }}"
      fields:
      - field: "{{ onepass_aws_admin_access_key_field }}"
        value: "<get access key from aws.amazom.com>"
        type: text
        prevent_overwrite: true
      - field: "{{ onepass_aws_admin_secret_field }}"
        value: "<get secret key from aws.amazom.com>"
        type: password
        prevent_overwrite: true
      - field: "URL"
        remove: true
      - field: "username"
        remove: true
      - field: "password"
        remove: true
      - section: "Admin Console"
        remove: true
      - section: "Hosting Provider"
        remove: true

  - name: Initialize 1Password with subdomain user secret
    when: onepass_enabled
    ansible.builtin.include_role:
      name: vault_utils_1password
      tasks_from: set_item.yml
    vars:
      category: server
      name: "{{ onepass_cluster_item }}"
      fields:  
      - field: "{{ onepass_pull_secret_field }}"
        section: common
        value: "<download pull secret, and update with playbooks/update_pull_secret.yml>"
        type: password
        prevent_overwrite: true
      - field: "URL"
        remove: true
      - field: "username"
        remove: true
      - field: "password"
        remove: true
      - section: "Admin Console"
        remove: true
      - section: "Hosting Provider"
        remove: true


