---

- name: Update the OpenShift pull secret in the vault
  hosts: client
  gather_facts: no
  tasks:

  - ansible.builtin.set_fact:
      pull_secret_path: ~/Downloads/pull-secret.txt

  - name: Check if pull-secret.txt exists in the ~/Downloads directory
    ansible.builtin.stat:
      path: "{{ pull_secret_path }}"
    register: pull_secret_stat

  - ansible.builtin.assert:
      that: pull_secret_stat.stat.exists
      fail_msg: "{{ pull_secret_path }} does not exist. Log into https://console.redhat.com/openshift/downloads/ and click 'download pull secret' at the bottom."
      success_msg: "{{ pull_secret_path }}"

  - name: Lookup pull secret contents
    ansible.builtin.set_fact:
      raw_pull_secret: "{{ lookup('file', pull_secret_path) | replace('\n','') | trim }}"

  - name: Encode pull secret
    ansible.builtin.set_fact:
      pull_secret_base64: "{{ raw_pull_secret | b64encode }}"

  - name: Show the pull secret
    ansible.builtin.debug:
      msg:
      - "raw pull secret: {{ raw_pull_secret }}"
      - "encoded pull secret: {{ pull_secret_base64 }}"

  - name: Update 1Password with subdomain user secrets
    when: onepass_enabled
    ansible.builtin.include_role:
      name: vault_utils_1password
      tasks_from: set_item.yml
    vars:
      category: server
      name: "{{ onepass_cluster_item }}"
      section: common
      fields: 
      - field: "{{ onepass_pull_secret_field }}"
        value: "{{ pull_secret_base64 }}"
