---

- name: Fetch secrets for the target cluster from 1Password
  hosts: client
  gather_facts: no
  tasks:

  - name: Fetch secrets
    ansible.builtin.set_fact:
      cacheable: true
      vault:
        route53_subdomain_user: "{{ lookup('community.general.onepassword', onepass_cluster_item, field=onepass_route53_subdomain_user_field, section=onepass_cluster_section) }}"
        route53_user_access_key_id: "{{ lookup('community.general.onepassword', onepass_cluster_item, field=onepass_aws_admin_access_key_field, section=onepass_cluster_section) }}"
        route53_user_secret_access_key: "{{ lookup('community.general.onepassword', onepass_cluster_item, field=onepass_aws_admin_secret_field, section=onepass_cluster_section) }}"
        route53_subdomain_user_arn: "{{ lookup('community.general.onepassword', onepass_cluster_item, field=onepass_route53_subdomain_user_arn, section=onepass_cluster_section) }}"
        github_pat: "{{ lookup('community.general.onepassword', onepass_cluster_item, field=onepass_github_pat_field, section='common') }}"
        openshift_pull_secret: "{{ lookup('community.general.onepassword', onepass_cluster_item, field=onepass_pull_secret_field, section='common') | b64decode | trim }}"
        # ssh_key_public: "{{ lookup('community.general.onepassword', onepass_cluster_item, field=onepass_ssh_key_public_field, section='common') | b64decode | trim }}"
        # ssh_key_private: "{{ lookup('community.general.onepassword', onepass_cluster_item, field=onepass_ssh_key_private_field, section='common') | b64decode | trim }}"

