---

- name: Create Single-Node OpenShift UTM VM on CSB macbook
  hosts: client
  gather_facts: no
  tasks:

  - name: Fetch secrets
    ansible.builtin.set_fact:
      cacheable: true
      vault:
        route53_user_access_key_id: "{{ lookup('community.general.onepassword', onepassword_vault_name, field='route53_jowest_access_key_id') }}"
        route53_user_secret_access_key: "{{ lookup('community.general.onepassword', onepassword_vault_name, field='route53_jowest_secret_access_key') }}"
        milabs_route53_hostedzone_id: "{{ lookup('community.general.onepassword', onepassword_vault_name, field='milabs_route53_hostedzone_id') }}"
        github_pat: "{{ lookup('community.general.onepassword', onepassword_vault_name, field='github_pat') }}"
        csb_ssh_public_key: "{{ lookup('community.general.onepassword', onepassword_vault_name, field='csb_ssh_public_key') | trim }}"
        openshift_pull_secret: "{{ lookup('community.general.onepassword', onepassword_vault_name, field='openshift_pull_secret_base64') | b64decode | trim }}"
