---

# consider adding backup of existing VM 

- name: Check if UTM directory exists 
  ansible.builtin.stat:
    path: "{{ clean_utm_vm_dir }}"
  register: utm_dir_status

- name: Delete the VM
  ignore_errors: true
  when: utm_dir_status.stat.exists
  ansible.builtin.shell: |
    osascript -e 'tell application "UTM"
      try
        set vm to virtual machine named "{{ clean_utm_vm_name }}"
        if status of vm is started then stop vm by force
        if vm exists then delete virtual machine named "{{ clean_utm_vm_name }}"
      on error
        return "VM {{ clean_utm_vm_name }} did not exist" 
      end try
    end tell'

- name: Delete the directory if it still exists
  when: utm_dir_status.stat.exists
  ansible.builtin.file:
    path: "{{ clean_utm_vm_dir }}"
    state: absent

