---

- name: Create {{ prep_utm_vm_name }}.utm directory  
  ansible.builtin.file:
    path: "{{ prep_utm_vm_dir }}"
    state: directory

- name: Create {{ prep_utm_vm_name }}.utm/Data directory  
  ansible.builtin.file:
    path: "{{ prep_utm_vm_dir }}/Data"
    state: directory

- name: Copy .ico files to UTM VM Data dir
  when: utm_icon_custom
  ansible.builtin.copy:
    src: "files/{{ utm_icon}}"
    dest: "{{ prep_utm_vm_dir }}/Data"
    remote_src: no
    mode: '0644'

