--- 

###
# Role arguments for setting secrets

# Required for settings and fetching a secret
name:             # Vault item name

# Optional for setting a secret
section:          # Section of the item for the field
category: login   # Category of secret - login | server  
type: password    # password | txt

# Set additional fields in item and section
fields:           
# - field:        # Field name in the vault item
#   type: text    # Type of field - text | password | url 
#   value:        # Value to set


###
# Settings to configure at client level of the inventory

# default 1Password CLI account
# - it is recommended ot use a separate account for automation so that automation can't get to your other secrets
onepass_account: my.1password.com

# Vault group name in 1Password the account has access to
# - the vault is the group within 1Password where items are created and fetched
onepass_vault: MILabs.io

