--- 

# 1Password documentation
# https://developer.1password.com/docs/cli/item-fields/

###
# Role arguments for setting secrets

# Required for settings and fetching a secret
name:             # Vault item name

# Optional for setting a secret
section:          # Section of the item for all the fields not explicitly set
category: login   # Category of secret - login | server | etc 
type: password    # password | txt

# Set additional fields in item and section
fields:      

# Set field
# - field: <field name/label>
#   [section:] <optional - section of the field>
#   type: <type of field - text | password | url>
#   value: <value to set>

# Set field defalt value, but don't overwrite
# - field:        # Field name in the vault item
#   type: text 
#   value: <default value> 
#   prevent_overwrite: true

# Remove field
# - field: <field label to delete>
#   [section:] <optional - section of the field>
#   remove: true

# Remove section
# - section: <section label to delete>
#   remove: true


###
# Settings to configure at client level of the inventory

# default 1Password CLI account
# - it is recommended ot use a separate account for automation so that automation can't get to your other secrets
onepass_account: my.1password.com

# Vault group name in 1Password the account has access to
# - the vault is the group within 1Password where items are created and fetched
onepass_vault: MILabs.io
