---

# required variables
sno_base_domain: 
sno_cluster_name: 
sno_ip_addr: 
sno_mac_addr: 
sno_ssh_key: 
sno_pull_secret: 

# staging
sno_staging_dir: "{{ role_path }}/../../target"
# sno_staging_dir: "/tmp"

# inferred variables
sno_agent_dir: "{{ sno_staging_dir }}/{{ sno_cluster_name }}"
sno_image_cache_dir: "{{ sno_staging_dir }}/image_cache"
sno_rhcos_image_name: "rhcos-{{ sno_arch }}-live.iso"
sno_mirror_dir: "{{ sno_staging_dir }}/mirror"

sno_api_dns: "api.{{ sno_cluster_name }}.{{ sno_base_domain }}"
sno_api_url: "https://{{ sno_api_dns }}:6443"
sno_apps_dns: "apps.{{ sno_cluster_name }}.{{ sno_base_domain }}"
sno_console_dns: "console-openshift-console.{{ sno_apps_dns }}"
sno_console_url: "https://{{ sno_console_dns }}"

# defaults
sno_version: 4.17.3
sno_imageset_ref: openshift-4.17
sno_type: openshift   # openshift | microshift
sno_arch: aarch64     # aarch64 | x86_64
sno_platform: none    # none | baremetal | vsphere
sno_root_device: /dev/vda
sno_net_interface: enp0s1
sno_dns_server: 8.8.8.8

macos_host_ip_addr: 127.0.0.1
macos_host_interface: en0
macos_host_gateway_ip_addr: 192.168.1.1

sno_machine_cidr_length: 24
sno_machine_prefix: "{{ macos_host_ip_addr | ansible.utils.ipsubnet( sno_machine_cidr_length ) | split('/') | first }}"
sno_ip_addr_reverse: "{{ sno_ip_addr.split('.') | reverse | join('.') }}"

macos_bonjour_service_enabled: false
macos_dnsmasq_enabled: true
