---

- name: Check if item field exists
  ignore_errors: true
  ansible.builtin.shell: |
    op item get '{{ name }}' \
      {{ account_arg | default('') }} {{ vault_arg | default('') }} \
      --fields '{{ field_section_prefix | default('') }}{{ item_field.field }}' \
      < /dev/null
  register: item_field_exists_output
 
- name: Determine status of the Vault Item from item_field_exists_output
  ansible.builtin.set_fact:
    item_field_exists: "{{ 't a field in the' not in item_field_exists_output.stderr }}"

