---

- name: Check if 1Password vault item and field exists
  ansible.builtin.include_role:
    name: vault_utils_1password
    tasks_from: vault_status.yml
  
- name: Form account CLI arg
  when: onepass_account is defined and onepass_account != ""
  ansible.builtin.set_fact:
    account_arg: "--account='{{ onepass_account }}'"

- name: Form vault CLI arg
  when: onepass_vault is defined and onepass_vault != ''
  ansible.builtin.set_fact:
    vault_arg: "--vault='{{ onepass_vault }}'"

- name: Form section CLI arg
  ansible.builtin.set_fact:
    section_prefix: "{{ section | default('') | replace('.', '-') }}."

- name: Create 1Password vault if does not exist
  when: not vault_item_exists
  ansible.builtin.shell: |
      op item create {{ account_arg | default('') }} {{ vault_arg | default('') }} \
        --title='{{ name }}' --category='{{ category | default('server') }}' \
        < /dev/null

- name: Set fields in the vault item
  with_items: "{{ fields }}" 
  loop_control:
    loop_var: item_field
  ansible.builtin.include_tasks: set_field.yml

