---

- name: Check if 1Password vault item and field exists
  ansible.builtin.include_role:
    name: vault_utils_1password
    tasks_from: vault_status.yml
  
- name: Form account CLI arg
  when: account is defined and account != ""
  ansible.builtin.set_fact:
    account_arg: "--account='{{ account }}'"

- name: Form vault CLI arg
  when: vault is defined and vault != ''
  ansible.builtin.set_fact:
    vault_arg: "--vault='{{ vault }}'"

- name: Form section CLI arg
  when: section is defined and section != ""
  ansible.builtin.set_fact:
    section_prefix: "{{ section }}."

- name: Create 1Password vault if does not exist
  when: not vault_item_exists
  ansible.builtin.shell: |
      op item create {{ account_arg | default('') }} {{ vault_arg | default('') }} \
        --title='{{ name }}' --category='{{ category | default('server') }}' \
        {{ section_prefix | default('') }}{{ field }}[{{ type | default('password') }}]='{{ value }}' \
        < /dev/null

- name: Set field if 1Password item does exist
  # when: vault_item_exists
  ansible.builtin.shell: |
    op item edit '{{ name }}' \
    {{ section_prefix | default('') }}{{ field }}[{{ type | default('password') }}]='{{ value }}' \
    < /dev/null

- name: Set additional fields if specified
  with_items: "{{ additonal_fields }}" 
  ansible.builtin.shell: |
    op item edit '{{ name }}' \
    {{ section_prefix | default('') }}{{ item.field }}[{{ item.type | default('password') }}]='{{ item.value }}' \
     < /dev/null 
    
