---

os_base_domain:
os_instance_name:
os_ip_addr:
os_mac_addr: 
os_ssh_key:

os_dist: rhel
os_version: 8.7
os_install_method: qcow2        # iso | qcow2
os_arch: aarch64                # aarch64 | x86_64

os_root_device: /dev/vda
os_net_interface: enp0s1



# virt-install
#     --name <vm_name> \
#     --autostart \
#     --memory=<memory> \
#     --cpu host \
#     --vcpus=<vcpus> \
#     --cdrom <agent_iso_image> \ 
#     --disk pool=default,size=<disk_pool_size> \
#     --network network:default,mac=<mac_address> \
#     --graphics none \
#     --noautoconsole \
#     --os-variant rhel9.0 \
#     --wait=-1
