apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: cert-manager-operator
  labels:
    kubernetes.io/metadata.name: cert-manager-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-13"
spec:
  finalizers:
  - kubernetes