apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: cert-manager-operator-group
  namespace: cert-manager-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-12"
spec:
  targetNamespaces:
  - cert-manager-operator
  upgradeStrategy: Default
  