apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: local-storage-operator-group
  namespace: openshift-local-storage
  annotations:
    argocd.argoproj.io/sync-wave: "-12"
spec:
  targetNamespaces:
  - openshift-local-storage
  upgradeStrategy: Default