---

- name: Configure AWS access account and credentials
  hosts: client
  gather_facts: no
  tasks:

  - name: Fetch secrets from 1Password
    when: onepass_enabled
    ansible.builtin.set_fact:
      route53_owner_access_key: "{{ lookup('community.general.onepassword', onepass_aws_admin_vault_item, field=onepass_aws_admin_access_key_field) }}"
      route53_owner_secret: "{{ lookup('community.general.onepassword', onepass_aws_admin_vault_item, field=onepass_aws_admin_secret_field) }}"


  - name: Gather facts for AWS subdomain
    ansible.builtin.set_fact:
      subdomain: "{{ cluster.subdomain }}"
      hostedzone: "{{ cluster.hostedzone }}"
      hostedzone_id: "{{ cluster.hostedzone_id }}"

  - debug: 
      msg: 
      - "route53_owner_access_key:  {{ route53_owner_access_key }}"
      - "route53_owner_secret:      {{ route53_owner_secret }}"
      - "subdomain:                 {{ subdomain }}"
      - "hostedzone:                {{ hostedzone }}"
      - "hostedzone_id:             {{ hostedzone_id }}"

  - name: Cleanup Route53 subdomain user account
    ansible.builtin.include_role:
      name: route53_owner
    vars:
      route53_owner_action: destroy
      route53_subdomain_name: "{{ subdomain }}"
      route53_hostedzone_name: "{{ hostedzone }}"
      route53_credentials_show: false

  - name: "Create Route53 subdomain user account for {{ subdomain }}.{{ hostedzone }}"
    ansible.builtin.include_role:
      name: route53_owner
    vars:
      route53_owner_action: create
      route53_subdomain_name: "{{ subdomain }}"
      route53_hostedzone_name: "{{ hostedzone }}"
      route53_credentials_show: "{{ not onepass_enabled }}"


  - name: Update 1Password with subdomain user secrets
    when: onepass_enabled
    ansible.builtin.include_role:
      name: vault_utils_1password
      tasks_from: set_item.yml
    vars:
      category: server
      section: "subdomain-{{ cluster.subdomain | replace('.','-') }}-{{ cluster.hostedzone | replace('.','-') }}"
      name: "{{ onepass_aws_admin_vault_item }}"
      field: route53_subdomain_user
      type: text
      value: "{{ route53_subdomain_user }}"
    with_items:
      - field: route53_subdomain_user_access_key
        type: text
        value: "{{ route53_subdomain_user_access_key }}"
      - field: route53_subdomain_user_secret
        type: password
        value: "{{ route53_subdomain_user_secret }}"
      - field: route53_subdomain_user_arn
        type: text
        value: "{{ route53_subdomain_user_arn }}"


