---

- name: Configure AWS access account
  hosts: localhost
  gather_facts: no
  tasks:

  - set_fact:
      onepassword_admin_vault_name: "milabs-admin"
      onepassword_vault_name: "milabs-secrets"
      subdomain: jowest
      hostedzone: milabs.io

  - name: Fetch secrets
    ansible.builtin.set_fact:
      route53_owner_access_key: "{{ lookup('community.general.onepassword', onepassword_admin_vault_name, field='aws_admin_access_key_id') }}"
      route53_owner_secret: "{{ lookup('community.general.onepassword', onepassword_admin_vault_name, field='aws_admin_secret_access_key') }}"
      route53_hostedzone_id: "{{ lookup('community.general.onepassword', onepassword_vault_name, field='milabs_route53_hostedzone_id') }}"
        
  - name: Cleanup Route53 subdomain user account
    ansible.builtin.include_role:
      name: route53_owner
    vars:
      route53_owner_action: destroy
      route53_subdomain_name: "{{ subdomain }}"
      route53_hostedzone_name: "{{ hostedzone }}"
      route53_credentials_write_vault: false
      route53_credentials_show: false

  - name: "Create Route53 subdomain user account for {{ subdomain }}.{{ hostedzone }}"
    ansible.builtin.include_role:
      name: route53_owner
    vars:
      route53_owner_action: create
      route53_subdomain_name: "{{ subdomain }}"
      route53_hostedzone_name: "{{ hostedzone }}"
      route53_credentials_write_vault: false
      route53_credentials_show: true
