---

- name: Get secrets from 1Password 
  when: onepass_enabled
  import_playbook: ./include/vault_cluster_onepass.yml

- name: Log into openshift, and set the context name
  hosts: client
  gather_facts: yes
  tasks:

  - name: Login to the target cluster
    ansible.builtin.shell: |
      oc login -u kubeadmin -p "{{ instance_kubeadmin }}" --server {{ instance_api_url }} --insecure-skip-tls-verify

  - name: Rename the kubectx to the cluster_name
    ansible.builtin.shell: |
      kubectx {{ cluster.cluster_name }}=$(kubectx -c)

