---

- name: Check prerequisites. Install automatable. Instruct manual how tos.
  hosts: client
  gather_facts: no
  tasks:

  # one password cli

  # required values in 1Password 
  # - openshift_pull_secret

  # On MacOS
  # - UTM 
  # - podman
  # - openshift-installer in /usr/local/bin
  # - oc client
  # - op 1Password client
  # optional:
  # - tekton
  # - odo
  # - helm
  # - argocd


# 1. Install UTM on MacOS
#    https://mac.getutm.app/ 
  
# 2. Install Podman / Podman Desktop for MacOS

# 3. Download command line tools and install to /usr/local/bin from https://console.redhat.com/openshift/downloads

#   - Ansible
#     `brew install ansible`
#   - OpenShift for arm insaller - MacOS / arm64
#     https://mirror.openshift.com/pub/openshift-v4/aarch64/clients/ocp/stable/openshift-install-mac-arm64.tar.gz
#   - OpenShift client
#     https://mirror.openshift.com/pub/openshift-v4/aarch64/clients/ocp/stable/openshift-client-mac-arm64.tar.gz
#     or `brew install openshift-cli`
#   - Helm 3 CLI
#     https://mirror.openshift.com/pub/openshift-v4/clients/helm/latest/helm-darwin-arm64.tar.gz
#     or `brew install helm`
#   - ODO Developer CLI for OpenShift
#     https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/odo/latest/odo-darwin-arm64.tar.gz
#     or `brew install odo`
#   - ArgoCD GitOps CLI
#     https://developers.redhat.com/content-gateway/rest/browse/pub/openshift-v4/clients/openshift-gitops/latest/argocd-macos-arm64.tar.gz
#     or `brew install argocd`
#   - Tekton CLI
#     https://mirror.openshift.com/pub/openshift-v4/clients/pipeline/latest/tkn-macos-arm64.tar.gz
#     or `brew install tektoncd-cli`
