---

- name: Init login secret in 1Password 
  when: onepass_enabled
  import_playbook: ./include/onepass_cluster_init.yml

- name: Get secrets from 1Password 
  when: onepass_enabled
  import_playbook: ./include/vault_cluster_onepass.yml

- name: Provision target cluster 
  hosts: client
  gather_facts: yes
  tasks:

  - name: Provision a Single-Node OpenShift cluster in MacOS on UTM
    when: cluster.type in  ('openshift','oke','ocp') and cluster.virtualization == 'UTM'
    ansible.builtin.include_role:
      name: sno_utm_route53
    vars:
      sno: "{{ cluster }}"
      route53_user_access_key_id: "{{ vault.route53_user_access_key_id }}"
      route53_user_secret_access_key: "{{ vault.route53_user_secret_access_key }}"
      openshift_pull_secret: "{{ vault.openshift_pull_secret }}"
      sno_ssh_key_public: "{{ ssh_key_public }}"

  # - name: Build a MicroShift cluster in MacOS on UTM
  #   when: cluster.type == 'microshift' and cluster.virtualization == 'UTM' 
  #   ansible.builtin.include_role:
  #     name: microshift_utm_route53
  #   vars:
  #     microshift: "{{ cluster }}"
  #     route53_user_access_key_id: "{{ vault.route53_user_access_key_id }}"
  #     route53_user_secret_access_key: "{{ vault.route53_user_secret_access_key }}"

- name: Set instance secrets in 1Password
  when: onepass_enabled
  import_playbook: include/onepass_cluster_populate.yml

- name: Show instance secrets
  when: not onepass_enabled
  import_playbook: include/instance_facts.yml

- name: Log into cluster and set kubectx name
  import_playbook: login_kubeadmin.yml

