---

- when: onepass_enabled
  import_playbook: ./include/vault-onepass.yml

- name: Provision target cluster 
  hosts: client
  gather_facts: no
  tasks:

  - name: Provision a Single-Node OpenShift cluster in MacOS on UTM
    when: cluster.type == 'openshift' and cluster.virtualization == 'UTM'
    ansible.builtin.include_role:
      name: sno_utm_route53
    vars:
      sno: "{{ cluster }}"
      route53_user_access_key_id: "{{ vault.route53_user_access_key_id }}"
      route53_user_secret_access_key: "{{ vault.route53_user_secret_access_key }}"


  # - name: Build a MicroShift cluster in MacOS on UTM
  #   when: cluster.type == 'microshift' and cluster.virtualization == 'UTM' 
  #   ansible.builtin.include_role:
  #     name: microshift_utm_route53
  #   vars:
  #     microshift: "{{ cluster }}"
  #     route53_user_access_key_id: "{{ vault.route53_user_access_key_id }}"
  #     route53_user_secret_access_key: "{{ vault.route53_user_secret_access_key }}"


  # - name: Update 1Password cluster login secret
  #   when: onepass_enabled
  #   ansible.builtin.include_role:
  #     name: vault_utils_1password
  #     tasks_from: set_item.yml
  #   vars:
  #     category: login
  #     name: "Login {{ cluster_full_name }}"
  #     fields:  
  #     - field: "password"
  #       value: "{{ kubeadmin_password }}"
  #       type: password
  #     - field: "password"
  #       value: "{{ cluster_ip_address }}"
  #       type: password
