---


# Microshift on Macbook Air with M3, 8 cores, 24GB RAM, 2TB SSD 
instance:
  cluster_name: airmshift
  vm_name: "Air MicroShift 4.17.4"  
  type: microshift         
  version: 4.17.4
  imageset: microshift-4.17 
  arch: aarch64   
  virtualization: UTM 
  apple_hypervisor: qemu                 
  cores: 10
  memory_gb: 18
  root_disk_gb: 200
  pvc_disk_gb: 200   
  subdomain: jowest       
  hostedzone: milabs.io
  hostedzone_id: Z04977272FB9P68H6O0NN 
  cidr_length: 24             
  icon: icon-k8s.ico   
  clean_image: true
  ssh_key_public_path: ~/.ssh/id_ed25519.pub
  ssh_key_private_path: ~/.ssh/id_ed25519

image_builder_vm:
  instance_name: airimgbldr
  vm_name: "Air Image Builder 8.7"
  image_path: "{{ lookup('env', 'HOME') }}/dev/archives/rh/rhel-8.7-aarch64-boot.iso"
  version: 8.7
  arch: aarch64
  virtualization: UTM 
  apple_hypervisor: qemu                
  cores: 2
  memory_gb: 4
  root_disk_gb: 100  
  subdomain: jowest       
  hostedzone: milabs.io
  hostedzone_id: Z04977272FB9P68H6O0NN 
  cidr_length: 24                 
  icon: icon-redhat.ico 
  ssh_key_public_path: ~/.ssh/id_ed25519.pub
  ssh_key_private_path: ~/.ssh/id_ed25519


rhel_instance: "{{ image_builder_vm }}"

onepass_vault_item: sno-local-secrets

ansible_user: core

ssh_key_public: "{{ lookup('file', instance.ssh_key_public_path) }}"
ssh_key_private: "{{ lookup('file', instance.ssh_key_private_path) }}"
