---

# SNO on Macbook Pro with M3 Pro, 12 cores, 360GB RAM, 1TB SSD 
instance:
  cluster_name: example
  vm_name: "example 4.17.4"  
  type: openshift         
  version: 4.17.4
  imageset: openshift-4.17       # For OCP openshift-4.x, for OKE use stable-4.x
  arch: aarch64   
  virtualization: UTM 
  apple_hypervisor: qemu                 
  cores: 10
  memory_gb: 18
  root_disk_gb: 200
  pvc_disk_gb: 200   
  subdomain: test       
  hostedzone: milabs.io
  hostedzone_id: P04977273FB9G68H6O0MM 
  cidr_length: 24             
  icon: icon-rhlayers.ico   
  clean_image: true
  ssh_key_public_path: ~/.ssh/id_ed25519.pub
  ssh_key_private_path: ~/.ssh/id_ed25519


onepass_vault_item: sno-local-secrets

ansible_user: core

ssh_key_public: "{{lookup('file', instance.ssh_key_public_path) }}"
ssh_key_private: "{{lookup('file', instance.ssh_key_private_path) }}"
