apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: openshift-storage
  labels:
    kubernetes.io/metadata.name: openshift-storage
    openshift.io/cluster-monitoring: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "-13"
spec:
  finalizers:
  - kubernetes
  