---

# Define your secrets and secure using an ansible vault in ~/.ansible/secrets/sno-local-admin-vault
admin_vault:
  route53_owner_access_key: 
  route53_owner_secret: 

# Lookup admin secrets from 1Password - used to create AWS IAM user
# - create the following keys in a 1Password vault as fields, naming fields to your preference
# - requires 1Password CLI installed and configured to use 1Password CLI 
# - running ansible will use your biometric authentication on macbook
# - secrets will be populated in the vault hierachy automatically   
admin_vault_1password_mapping:
  route53_owner_access_key:
    vault_name: milabs-secrets
    vault_field: aws_admin_access_key_id
  route53_owner_secret:
    vault_name: milabs-secrets
    vault_field: aws_admin_secret_access_key
