---

- name: Prepare the agent directory
  ansible.builtin.include_role:
    name: sno_agent
    tasks_from: prep.yml

- name: Generate agent-config.yaml
  ansible.builtin.template:
    src: templates/agent-config.yaml.j2
    dest: "{{ sno_agent_dir }}/agent-config.yaml"
    mode: '0644'

- name: Generate install-config.yaml
  ansible.builtin.template:
    src: templates/install-config.yaml.j2
    dest: "{{ sno_agent_dir }}/install-config.yaml"
    mode: '0644'

- name: Generate agent containerfile
  ansible.builtin.template:
    src: templates/Containerfile
    dest: "{{ sno_agent_dir }}/Containerfile"
    mode: '0644'

- name: Build agent container image
  ansible.builtin.shell: |
    export OCP_VERSION={{ sno_version }}
    podman build -f {{ sno_agent_dir }}/Containerfile -t openshift-install --build-arg VERSION=${OCP_VERSION}

- name: Create image
  ansible.builtin.shell: |
    podman run --privileged --rm \
        -v {{ sno_agent_dir }}:/data \
        -v {{ sno_agent_dir }}/image_cache:/root/.cache/agent/image_cache \
        -v {{ sno_agent_dir }}/files_cache:/root/.cache/agent/files_cache \
        -w /data openshift-install:latest --dir ./ \
        agent create image

- name: Emit sno_boot_iso for use at host level
  ansible.builtin.set_fact:
    cacheable: true
    sno_boot_iso: "{{ sno_agent_dir }}/agent.{{ sno_arch }}.iso"


