---

- import_tasks: hypervisor_facts.yml

- name: Gather SNO Agent facts for use at playbook level
  ansible.builtin.set_fact:
    cacheable: true
    sno_staging_dir: "{{ sno_staging_dir }}"
    sno_agent_dir: "{{ sno_agent_dir }}"
    sno_api_url: "{{ sno_api_url }}"
    sno_console_url: "{{ sno_console_url }}"
    sno_oauth_url: "{{ sno_oauth_url }}"
    sno_kubeadmin_pass_path: "{{ sno_agent_dir }}/auth/kubeadmin-password"
    sno_kubeconfig_path: "{{ sno_agent_dir }}/auth/kubeconfig"
    
- name: Get contents of kubeadmin-password and kubeconfig
  ansible.builtin.set_fact:
    cacheable: true
    sno_kubeadmin_pass: "{{ lookup('file', sno_kubeadmin_pass_path) }}"
    sno_kubeconfig: "{{ lookup('file', sno_kubeconfig_path) }}"
