---

- name: "Wait for bootstrap complete"
  ansible.builtin.shell: |
    export KUBECONFIG={{ sno_agent_dir }}/auth/kubeconfig
    openshift-install --dir={{ sno_agent_dir }} agent wait-for bootstrap-complete > {{ sno_agent_dir }}/wait-bootstrap.log
    cat {{ sno_agent_dir }}/wait-bootstrap.log
  register: bootstrap_complete_output

- name: "Show wait-bootstrap.log"
  debug: 
    msg: 
    - "{{ bootstrap_complete_output.stdout }}"
    - "Automatically Rebooting Node..."

# UTM VM will automatically reboot now

- name: "Wait for install complete"
  ansible.builtin.shell: |
    export KUBECONFIG={{ sno_agent_dir }}/auth/kubeconfig
    openshift-install --dir={{ sno_agent_dir }} wait-for install-complete > {{ sno_agent_dir }}/install-complete.log
    cat {{ sno_agent_dir }}/install-complete.log
  register: install_complete_output

- name: "Show install-complete.log"
  debug: 
    msg: 
    - "{{ install_complete_output.stdout }}"


