---

- name: Show host ansible facts
  hosts: localhost
  gather_facts: yes
  tasks:

  - debug: 
      msg: 
      - "ansible_distribution           {{ ansible_distribution }}"
      - "ansible_distribution_release   {{ ansible_distribution_release }}"
      - "ansible_distribution_version   {{ ansible_distribution_version }}"
      - "ansible_os_family              {{ ansible_os_family }}"
      - "ansible_machine                {{ ansible_machine }}"
      - "ansible_architecture           {{ ansible_architecture }}"



