---


- name: Create Single-Node OpenShift UTM VM
  hosts: localhost
  gather_facts: no
  tasks:

  - name: Fetch UTM VM Info
    ansible.builtin.include_role:
      name: utm
      tasks_from: info.yml
    vars:
      utm_vm_name: sno-csb-arm1

  - name: Gather hypervisor host facts
    ansible.builtin.include_role:
      name: sno_agent
      tasks_from: hypervisor_facts.yml
