---


- name: Create Single-Node OpenShift UTM VM
  hosts: localhost
  gather_facts: no
  tasks:

  - name: Fetch UTM VM Info
    ansible.builtin.include_role:
      name: utm
      tasks_from: info.yml
    vars:
      utm_vm_name: sno-csb-arm

  - name: Show status
    debug: 
      msg: 
      - "utm_vm_dir_exists: {{ utm_vm_dir_exists }}"
      - "utm_vm_exists: {{ utm_vm_exists }}"
      - "utm_vm_started: {{ utm_vm_started }}"
      - "utm_vm_ip_addr: {{ utm_vm_ip_addr }}"
      - "utm_vm_mac_addr: {{ utm_vm_mac_addr }}"


