---

- name: Create Single-Node OpenShift UTM VM
  hosts: localhost
  gather_facts: no
  tasks:

  - name: Fetch secrets
    ansible.builtin.set_fact:
      vault:
        aws_admin_access_key_id: "{{ lookup('community.general.onepassword', 'milabs-admin', field='aws_admin_access_key_id') }}"
        aws_admin_secret_access_key: "{{ lookup('community.general.onepassword', 'milabs-admin', field='aws_admin_secret_access_key') }}"
        route53_user_access_key_id: "{{ lookup('community.general.onepassword', 'milabs-secrets', field='route53_user_access_key_id') }}"
        route53_user_secret_access_key: "{{ lookup('community.general.onepassword', 'milabs-secrets', field='route53_user_secret_access_key') }}"
        github_pat: "{{ lookup('community.general.onepassword', 'milabs-secrets', field='github_pat') }}"
        csb_ssh_public_key: "{{ lookup('community.general.onepassword', 'milabs-secrets', field='csb_ssh_public_key') }}"
        air_ssh_public_key: "{{ lookup('community.general.onepassword', 'milabs-secrets', field='air_ssh_public_key') }}"
        openshift_pull_secret: "{{ lookup('community.general.onepassword', 'milabs-secrets', field='openshift_pull_secret_base64') | b64decode }}"

  - name: Generate template and show the output for install-config.yaml.j2
    vars:
      sno_base_domain: local.milabs.io
      sno_cluster_name: mycluster
      sno_pull_secret: "{{ vault.openshift_pull_secret }}"
      sno_ssh_key: "{{ vault.csb_ssh_public_key }}"
    debug: 
      msg: 
      - | 
        "{{ lookup('template', playbook_dir + '/../../roles/sno_agent/templates/install-config.yaml.j2') }}"


