---

- name: Route53 records
  debug:
    msg: "{{ route53_subdomain_records }}"

- name: Create/Update Route53 records
  with_items: "{{ route53_subdomain_records }}"
  loop_control:
    loop_var: recname
  vars: 
    dnsrecord: "{{ route53_subdomain_records[recname] }}"
  amazon.aws.route53:
    aws_access_key: "{{ route53_subdomain_user_access_key }}"
    aws_secret_key: "{{ route53_subdomain_user_secret }}"
    state: present
    record: "{{ dnsrecord.record }}"
    value: "{{ dnsrecord.value }}"
    zone: "{{ dnsrecord.zone }}"
    type: "{{ dnsrecord.type }}"
    ttl: 7200
    overwrite: yes
    wait: "{{ route53_register_wait }}"

