--- 

sno:
  cluster_name: sno
  vm_name: sno-arm1
  type: openshift                   # openshift | microshift
  hostedzone: milabs.io
  base_domain: local.milabs.io
  version: 4.17.3
  imageset: openshift-4.17
  cidr_length: 24       
  arch: aarch64                     # aarch64 | x86_64
  cores: 10
  memory_gb: 18
  root_disk_gb: 200
  pvc_disk_gb: 200 
  clean_image: true
  icon: icon-rhlayers.ico           # icon-k8s.ico | icon-microservice.ico | icon-microshift.ico | icon-ocp.ico | icon-redhat.ico | icon-rhlayers.ico
  
